### ISSUE TITLE
Changer la façon de faire les fetch

### ISSUE THREAD

**Issue by RomainZieba** [AezardSR/Le_Flamant_Bleu#43]
Rendre opaque le procédé des fetch.
L"idée est de passer par une fonction et y passer en paramètre la route API.

avant:
```js
    const fetchUser = () => {
            fetch(`${process.env.REACT_APP_API_PATH}/user-profile`, {
            method: 'GET',
            headers: {
                'content-type': 'application/json',
                'Authorization' : 'bearer ' + token
            }
            }).then((res) => (
                res.json()
            )).then((data) => {
                setUser(data)
            })
    }
```
après : 
```js
    const fetchUser = () => {
            requestAPI('/user-profile', 'GET', null).then((res) => (
                res.json()
            )).then((data) => {
                setUser(data)
            })
    }
```
il ne faut pas oublié également l'import de la fonction du context :

```js
const { requestAPI } = useContext(ApiContext);
```

**Comment by RomainZieba** [comment]
Voila pour la fonction : 
```js
  // Fonction qui check si le token est valide
    const checkToken = new Promise((resolve, reject) => {
        const authTokens = localStorage.getItem('token') ? JSON.parse(localStorage.getItem('token')) : null;
        const accessToken = jwt_decode(authTokens? authTokens : null);
        const isExpired = dayjs.unix(accessToken.exp).diff(dayjs()) < 1;
        isExpired ? reject("token expiré") : resolve(isExpired);
    })
    // Fonction permettant les requêtes à l'API, avec une facilité d'utilisation au niveau des paramètres headers et body
    const requestAPI = (url, method, body) => {
        return new Promise((resolve, reject) => {
         checkToken.then(() => {
            console.log("token valide")
            if(body === null){
                resolve( fetch(`${process.env.REACT_APP_API_PATH}${url}`, {
                    method: method,
                    headers: {
                        'content-type': 'application/json',
                        'Authorization' : 'bearer ' + token
                    },
                }))
            } else {
                resolve( fetch(`${process.env.REACT_APP_API_PATH}${url}`, {
                    method: method,
                    headers: {
                        'content-type': 'application/json',
                        'Authorization' : 'bearer ' + token
                    },
                    body: JSON.stringify(body)
                }))
            }
        }).catch((error) => {
            navigate('/login')
            reject(error)
        })
    })}
```
"url" : correspond au chemin API que vous voulez toucher.
"méthode" : Correspond au type de méthode utilisé (post, get, etc ...)
"body" : correspond au contenu de type body de la requête (exemple les information envoyer par un formulaire)

Dans de cas ou la requête n'a pas de body, il faut impérativement passer le paramètre "null" pour le body.

**Comment by Manon-POTEL** [comment]
> Voila pour la fonction :
> 
> ```js
>     const requestAPI = (url, method, body) => {
>         if(body === null){
>             return fetch(`${process.env.REACT_APP_API_PATH}${url}`, {
>                 method: method,
>                 headers: {
>                     'content-type': 'application/json',
>                     'Authorization' : 'bearer ' + token
>                 },
>             })
>         }else {
>             return fetch(`${process.env.REACT_APP_API_PATH}${url}`, {
>                 method: method,
>                 headers: {
>                     'content-type': 'application/json',
>                     'Authorization' : 'bearer ' + token
>                 },
>                 body: JSON.stringify(body)
>             })
> }}
> ```
> 
> "url" : correspond au chemin API que vous voulez toucher. "méthode" : Correspond au type de méthode utilisé (post, get, etc ...) "body" : correspond au contenu de type body de la requête (exemple les information envoyer par un formulaire)
> 
> Dans de cas ou la requête n'a pas de body, il faut impérativement passer le paramètre "null" pour le body.

Function a ajouter dans un fichier .js ou a copié collé à chaque fois ?
